apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    app.kubernetes.io/instance: guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: guestbook
  name: yo2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: guestbook
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook
    app.kubernetes.io/instance: guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: guestbook
  name: heya1
spec:
  replicas: 12
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: guestbook
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: guestbook
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: helm-guestbook
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
